import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import "./styles/style.css";
import "./styles/responsive.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900|Source+Sans+Pro:300,400,600,700,900" />
        <link rel="stylesheet" href="/vendor/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/vendor/Camera-master/css/camera.css" />
        <link rel="stylesheet" href="/vendor/menu/dist/css/slimmenu.css" />
        <link rel="stylesheet" href="/fonts/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="/vendor/owl-carousel/owl.carousel.css" />
        <link rel="stylesheet" href="/vendor/owl-carousel/owl.theme.css" />
        <link rel="stylesheet" href="/vendor/WOW-master/css/libs/animate.css" />
        <link rel="stylesheet" href="/fonts/icon/font/flaticon.css" />
        <link rel="stylesheet" href="/vendor/fancybox/dist/jquery.fancybox.min.css" />
        <link rel="stylesheet" href="/vendor/language-switcher/polyglot-language-switcher.css" />
        <link rel="stylesheet" href="/vendor/sanzzy-map/dist/snazzy-info-window.min.css" />
      </head>
      <body>
        <div className="main-page-wrapper">
          <Header />
          {children}
          <Footer />
        </div>

        {/* Scripts */}
        <Script src="/vendor/jquery.2.2.3.min.js" strategy="beforeInteractive" />
        <Script src="/vendor/popper.js/popper.min.js" />
        <Script src="/vendor/bootstrap/js/bootstrap.min.js" />
        <Script src="/vendor/Camera-master/scripts/jquery.mobile.customized.min.js" />
        <Script src="/vendor/Camera-master/scripts/jquery.easing.1.3.js" />
        <Script src="/vendor/Camera-master/scripts/camera.min.js" />
        <Script src="/vendor/menu/src/js/jquery.slimmenu.js" />
        <Script src="/vendor/WOW-master/dist/wow.min.js" />
        <Script src="/vendor/owl-carousel/owl.carousel.min.js" />
        <Script src="/vendor/jquery.appear.js" />
        <Script src="/vendor/jquery.countTo.js" />
        <Script src="/vendor/fancybox/dist/jquery.fancybox.min.js" />
        <Script src="/vendor/language-switcher/jquery.polyglot.language.switcher.js" />
        <Script src="/js/theme.js" />
        <Script src="/js/map-script.js" />
      </body>
    </html>
  );
}
